version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - npm install -g mocha
  pre_build:
    commands:
     - npm install
  build:
    commands:
      - npm run build
      - npm run test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
